---
booktitle: Proceedings of The 26th International Conference on Artificial Intelligence
  and Statistics
shortname: AISTATS
volume: '206'
year: '2023'
start: &1 2023-04-25
end: 2023-04-27
published: 2023-04-11
location: Valencia, Spain
conference_number: '26'
sections:
- name: Notable Papers
  title: Notable Papers
- name: Regular Papers
  title: Regular Papers
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: AISTATS-2023
month: 0
cycles: false
bibtex_editor: Ruiz, Francisco and Dy, Jennifer and van de Meent, Jan-Willem
editor:
- given: Francisco
  family: Ruiz
- given: Jennifer
  family: Dy
- given: Jan-Willem
  family: Meent
  prefix: van de
title: Proceedings of Machine Learning Research
description: |
  Proceedings of The 26th International Conference on Artificial Intelligence and Statistics
    Held in Palau de Congressos, Valencia, Spain on 25-27 April 2023

  Published as Volume 206 by the Proceedings of Machine Learning Research on 11 April 2023.

  Volume Edited by:
    Francisco Ruiz
    Jennifer Dy
    Jan-Willem van de Meent

  Series Editors:
    Neil D. Lawrence
date_str: 25--27 Apr
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v206"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: mlresearch/jekyll-theme
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v206
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v206
email: ''
conference:
  name: International Conference on Artificial Intelligence and Statistics
  url: http://aistats.org/aistats2023/
  location: Palau de Congressos, Valencia, Spain
  dates:
  - *1
  - 2023-04-26
  - 2023-04-27
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/Users/neil/mlresearch/v206/aistats23.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/v206/aistats23.bib
